### ISSUE TITLE
Doesnt show ROC curve

### ISSUE THREAD

**Issue by Apooravdwn** [pranavms13/Credit-Card-Fraud-Detection#1]
not showing the roc curve . can you provide the full code to get roc curve

**Comment by pranavms13** [comment]
please check it again. it plots the roc at last

**Comment by Apooravdwn** [comment]
can i have your whatsapp no plzz it will easy to communicate

**Comment by Apooravdwn** [comment]
so i can sahre the code and then will rectify it please

**Comment by Apooravdwn** [comment]
i really want to understand this

**Comment by pranavms13** [comment]
> can i have your whatsapp no plzz it will easy to communicate

you can contact me on telegram t.me/pranavms

**Comment by pranavms13** [comment]
> so i can sahre the code and then will rectify it please

fork the repo, rectify it and open a PR
